### ISSUE TITLE
figure out a county level census call for population data (or state level call that includes the counties)

### ISSUE THREAD

**Issue by rebgrasshopper** [clydebaron2000/Project1#2]
help, I'm struggling

**Comment by ajlb** [comment]
api.census.gov/data/2019/pep/population?key=45876004e2fbfafe56615f040f2172ee79c77643&get=POP&in=state:06&for=county:003

get method

state 06 is CA

county 003 is Alpine

**Comment by ajlb** [comment]
api.census.gov/data/2019/pep/population?key=45876004e2fbfafe56615f040f2172ee79c77643&get=POP&in=state:06&for=county:*

method get

returns all population data for every county in California
