### ISSUE TITLE
Clyde - do you want to make an option for the slider to work for 14 day values (which shows current cases) or for 7 day values (which would show latest trends)? Give people an option? I can change the code to pull out 7 day data as well.

### ISSUE THREAD

**Issue by rebgrasshopper** [clydebaron2000/Project1#33]

**Comment by clydebaron2000** [comment]
7 day data as in the last 7 days? 
in either case, yes

**Comment by rebgrasshopper** [comment]
Ok, I've got all the data set up. Any more desired can be pulled out at will. I'm gonna call this part done, since the rest is just subsumed into the general creation of the slider.
