### ISSUE TITLE
Covid Data 

### ISSUE THREAD

**Issue by jen6one9** [clydebaron2000/Project1#4]
1. Obtain current Covid 19 data 
2. Extract elements we need 
3. Obtain geo reference for county name  *reminder: we won't be able to see the coordinates 
4. Capture time stamp

**Comment by ajlb** [comment]
CA.gov open data portal:
https://data.ca.gov/dataset/covid-19-cases/resource/926fd08f-cc91-4828-af38-bd45de97f8c3

Resource ID will change daily
To query use &q
Query example:https://data.ca.gov/api/3/action/datastore_search?resource_id=926fd08f-cc91-4828-af38-bd45de97f8c3&q=San Diego
