### ISSUE TITLE
Dry run presentation

### ISSUE THREAD

**Issue by rebgrasshopper** [clydebaron2000/Project1#48]
who is doing what?
Practice run

**Comment by jen6one9** [comment]
Version 1 of the outline is done.   Team will time ourselves during the dry runs and make edits to finalize.

**Comment by jen6one9** [comment]
https://docs.google.com/document/d/1JHG734xtvxi-ZBpfJJY_AxWVVkdpUsA3xFxilwjpcEw/edit
